quarkus.log.file.enabled = true

#
# Camel - Main
#
camel.main.duration-hit-exit-code = 15

#
# Camel - Components
#
camel.component.log.exchange-formatter = #class:org.apache.camel.support.processor.DefaultExchangeFormatter
camel.component.log.exchange-formatter.show-exchange-pattern = false
camel.component.log.exchange-formatter.show-body-type = false

#
# Integration
#
timer.period = 5000

# IBM MQ
ibm.mq.host=localhost
ibm.mq.port=1414
ibm.mq.channel=DEV.APP.SVRCONN
ibm.mq.queueManagerName=QM1
ibm.mq.user=app
ibm.mq.password=passw0rd
ibm.mq.queue=DEV.QUEUE.1

# ActiveMQ
activemq.brokerURL=tcp://localhost:61616
activemq.user=admin
activemq.password=admin